name: Build Geode Mod

# This tells GitHub to run the build whenever you push code, 
# or when you manually trigger it from the Actions tab.
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Uses the official Geode SDK action to handle all the complex C++ setup
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          target: ${{ matrix.config.target }}

  package:
    name: Package Geode Mod
    runs-on: ubuntu-latest
    needs: build # Waits for all platforms to finish building

    steps:
      # Combines the Windows, Mac, and Android builds into one .geode file
      - name: Combine Builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extrapolation-Mod-Build
          path: ${{ steps.build.outputs.build-output }}
